# Generated by Django 4.1 on 2022-08-20 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_coderhouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='cumpleaños',
            new_name='cumpleanios',
        ),
    ]
