# Generated by Django 4.1 on 2022-08-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_coderhouse', '0003_familiar_parentesco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='cumpleanios',
            field=models.DateField(blank=True, null=True),
        ),
    ]
