# Generated by Django 4.1 on 2022-08-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_coderhouse', '0005_remove_familiar_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='cumpleanios',
        ),
        migrations.AddField(
            model_name='familiar',
            name='edad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
