# Generated by Django 4.1 on 2022-08-20 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_coderhouse', '0006_remove_familiar_cumpleanios_familiar_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='edad',
        ),
    ]
