# Generated by Django 4.1 on 2022-08-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_coderhouse', '0007_remove_familiar_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='cumpleanios',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familiar',
            name='edad',
            field=models.IntegerField(null=True),
        ),
    ]
