# Generated by Django 4.1 on 2022-08-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_coderhouse', '0008_familiar_cumpleanios_familiar_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='ocupacion',
            field=models.CharField(default=' ', max_length=80),
            preserve_default=False,
        ),
    ]
